-- ===================================================
-- LUMNG Initial Migration
-- Generated by: npx prisma migrate dev --name init
-- Run manually: psql $DATABASE_URL < this_file.sql
-- Or just run: npm run db:migrate
-- ===================================================

-- CreateEnum
CREATE TYPE "DeliveryMode" AS ENUM ('DELIVERY', 'PICKUP');
CREATE TYPE "OrderStatus"  AS ENUM ('PENDING', 'CONFIRMED', 'PROCESSING', 'FULFILLED', 'CANCELLED');

-- CreateTable: products
CREATE TABLE "products" (
    "id"          SERIAL       NOT NULL,
    "name"        TEXT         NOT NULL,
    "category"    TEXT         NOT NULL,
    "description" TEXT         NOT NULL DEFAULT '',
    "price"       DOUBLE PRECISION NOT NULL,
    "unit"        TEXT         NOT NULL DEFAULT 'per yard',
    "minOrder"    INTEGER      NOT NULL DEFAULT 1,
    "bulkPrice"   DOUBLE PRECISION,
    "bulkMin"     INTEGER,
    "badge"       TEXT,
    "pattern"     TEXT         NOT NULL DEFAULT 'linear-gradient(135deg,#1a1a1a,#333)',
    "imageUrl"    TEXT,
    "inStock"     BOOLEAN      NOT NULL DEFAULT true,
    "featured"    BOOLEAN      NOT NULL DEFAULT false,
    "tags"        TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"   TIMESTAMP(3) NOT NULL,
    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);

-- CreateTable: orders
CREATE TABLE "orders" (
    "ref"          TEXT         NOT NULL,
    "custName"     TEXT         NOT NULL,
    "custEmail"    TEXT         NOT NULL,
    "custPhone"    TEXT         NOT NULL,
    "custAddress"  TEXT,
    "custState"    TEXT,
    "custLandmark" TEXT,
    "pickupDate"   TEXT,
    "delivery"     "DeliveryMode" NOT NULL DEFAULT 'DELIVERY',
    "subtotal"     DOUBLE PRECISION NOT NULL,
    "deliveryFee"  DOUBLE PRECISION NOT NULL DEFAULT 0,
    "total"        DOUBLE PRECISION NOT NULL,
    "status"       "OrderStatus"  NOT NULL DEFAULT 'PENDING',
    "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"    TIMESTAMP(3) NOT NULL,
    CONSTRAINT "orders_pkey" PRIMARY KEY ("ref")
);

-- CreateTable: order_items
CREATE TABLE "order_items" (
    "id"        SERIAL           NOT NULL,
    "orderId"   TEXT             NOT NULL,
    "productId" INTEGER          NOT NULL,
    "qty"       INTEGER          NOT NULL,
    "unitPrice" DOUBLE PRECISION NOT NULL,
    CONSTRAINT "order_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable: admins
CREATE TABLE "admins" (
    "id"           SERIAL NOT NULL,
    "username"     TEXT   NOT NULL,
    "passwordHash" TEXT   NOT NULL,
    CONSTRAINT "admins_pkey" PRIMARY KEY ("id")
);

-- CreateTable: settings
CREATE TABLE "settings" (
    "key"       TEXT         NOT NULL,
    "value"     JSONB        NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "settings_pkey" PRIMARY KEY ("key")
);

-- CreateIndex
CREATE UNIQUE INDEX "admins_username_key" ON "admins"("username");

-- AddForeignKey: order_items → orders
ALTER TABLE "order_items"
  ADD CONSTRAINT "order_items_orderId_fkey"
  FOREIGN KEY ("orderId") REFERENCES "orders"("ref")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey: order_items → products
ALTER TABLE "order_items"
  ADD CONSTRAINT "order_items_productId_fkey"
  FOREIGN KEY ("productId") REFERENCES "products"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;
